#ifndef _CONF_H_
#define _CONF_H_
#include "generated/autoconf.h"

#define EXEC_WAIT_POLICY (resume_cnt <= suspend_cnt)

#ifndef CONFIG_COMPONENT_COROUTINE

#define USE_IDLE_TASK
#define MAX_TASK_NUM 10

#define USE_CTX
#define TASK_CTX_SIZE 64

#else

#ifdef CONFIG_COMPONENT_COROUTINE_USE_IDLE_TASK
#define USE_IDLE_TASK
#endif

#ifdef CONFIG_COMPONENT_COROUTINE_MAX_TASK_NUM
#define MAX_TASK_NUM CONFIG_COMPONENT_COROUTINE_MAX_TASK_NUM
#endif

#ifdef CONFIG_COMPONENT_COROUTINE_USE_CTX
#define USE_CTX
#endif

#ifdef CONFIG_COMPONENT_COROUTINE_TASK_CTX_SIZE
#define TASK_CTX_SIZE CONFIG_COMPONENT_COROUTINE_TASK_CTX_SIZE
#endif

#endif

#endif